/* scripts/generateCourses.js
 *
 * Scans src/Pages/courses/<Track>/*.md and emits src/utils/foundationsCoursesData.js,
 * the data module the Foundations page reads from. This is what makes courses "pulled
 * from the folder": drop a new .md into a track folder and it shows up on next build.
 *
 * Runs automatically before `npm start` and `npm run build` (see package.json prestart
 * / prebuild). You can also run it by hand: `node scripts/generateCourses.js`.
 *
 * Per-file metadata is derived from the markdown itself:
 *   title    -> the first "# " heading
 *   summary  -> the first normal paragraph after the title
 *   projects -> count of "## " sections (projects + capstone)
 * Optional ordering: put an HTML comment "<!-- order: 2 -->" near the top of a file to
 * control where it appears in its track. Files without an order sort after ordered ones,
 * alphabetically.
 */

const fs = require('fs');
const path = require('path');

const COURSES_DIR = path.join(__dirname, '..', 'src', 'Pages', 'courses');
const OUT_FILE = path.join(__dirname, '..', 'src', 'utils', 'foundationsCoursesData.js');

const firstHeading = (md) => {
  const m = md.match(/^#\s+(.+?)\s*$/m);
  return m ? m[1].trim() : null;
};

const firstParagraph = (md) => {
  const lines = md.split('\n');
  let seenTitle = false;
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i].trim();
    if (!seenTitle) {
      if (line.startsWith('# ')) seenTitle = true;
      continue;
    }
    if (!line) continue;
    // Skip headings, rules, list markers, code fences, blockquotes.
    if (/^(#|---|\*\*\*|```|>|[-*+]\s|\d+\.\s)/.test(line)) continue;
    // Strip simple markdown emphasis so the card summary reads cleanly.
    const clean = line.replace(/\*\*/g, '').replace(/\*/g, '').replace(/`/g, '').trim();
    return clean.length > 240 ? clean.slice(0, 237).trimEnd() + '...' : clean;
  }
  return '';
};

const readOrder = (md) => {
  const m = md.match(/<!--\s*order:\s*(\d+)\s*-->/i);
  return m ? parseInt(m[1], 10) : null;
};

const countProjects = (md) => {
  const m = md.match(/^##\s+/gm);
  return m ? m.length : 0;
};

const build = () => {
  const result = {};
  if (!fs.existsSync(COURSES_DIR)) {
    fs.writeFileSync(OUT_FILE, moduleText({}));
    console.log('[generateCourses] no courses dir; wrote empty data module.');
    return;
  }
  const tracks = fs.readdirSync(COURSES_DIR, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name);

  tracks.forEach((track) => {
    const dir = path.join(COURSES_DIR, track);
    const files = fs.readdirSync(dir).filter((f) => f.toLowerCase().endsWith('.md'));
    const courses = files.map((file) => {
      const md = fs.readFileSync(path.join(dir, file), 'utf8');
      const slug = file.replace(/\.md$/i, '');
      return {
        slug,
        title: firstHeading(md) || slug,
        summary: firstParagraph(md),
        projects: countProjects(md),
        order: readOrder(md),
        markdown: md,
      };
    });
    courses.sort((a, b) => {
      const ao = a.order == null ? Infinity : a.order;
      const bo = b.order == null ? Infinity : b.order;
      if (ao !== bo) return ao - bo;
      return a.title.localeCompare(b.title);
    });
    // Drop the internal `order` field from the shipped data; it has done its job.
    if (courses.length) result[track] = courses.map(({ order, ...c }) => c);
  });

  fs.writeFileSync(OUT_FILE, moduleText(result));
  const total = Object.values(result).reduce((n, arr) => n + arr.length, 0);
  console.log(`[generateCourses] wrote ${total} course(s) across ${Object.keys(result).length} track(s).`);
};

const moduleText = (obj) =>
  '// AUTO-GENERATED by scripts/generateCourses.js. Do not edit by hand.\n' +
  '// Edit the .md files under src/Pages/courses/<Track>/ instead, then rebuild.\n\n' +
  'export const COURSES_BY_TRACK = ' + JSON.stringify(obj, null, 2) + ';\n';

build();
